include /etc/nginx/modules-enabled/*.conf;

env CLICKHOUSE_HOST;
env CLICKHOUSE_PORT;
env CLICKHOUSE_DB;
env CLICKHOUSE_TABLE;
env SERVICE_NAME;
env AWS_REGION;
env S3_BUCKET;
env AWS_ACCESS_KEY_ID;
env AWS_SECRET_ACCESS_KEY;

worker_processes auto;

events {}

http {

    access_log /dev/stdout;
    error_log  /dev/stderr notice;

    resolver 127.0.0.11 ipv6=off;

    lua_package_path "/etc/nginx/lua/?.lua;;";

    lua_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
    lua_ssl_verify_depth 5;

    client_max_body_size 20m;
    client_body_buffer_size 20m;

    server {
        listen 8080;

        location /stub_status {
            stub_status;
            allow 127.0.0.1;
            deny all;
        }
    }

    upstream dapi {
        server dapi.xxx.com:443;
    }

    upstream dfr {
        server dfr.xxx.com:443;
    }

    server {
        listen 80;

        #resolver 8.8.8.8;

        # Dummy endpoint untuk testing upload besar
        location /test-upload {
            # Capture request body dan response untuk S3
            access_by_lua_block {
                ngx.req.read_body()
                ngx.ctx.req_body = ngx.req.get_body_data() or ""
            }

            body_filter_by_lua_block {
                local chunk = ngx.arg[1]
                if not ngx.ctx.resp_body then
                    ngx.ctx.resp_body = chunk or ""
                else
                    ngx.ctx.resp_body = ngx.ctx.resp_body .. (chunk or "")
                end
            }

            log_by_lua_file /etc/nginx/lua/send_log.lua;

            content_by_lua_block {
                ngx.status = 200
                ngx.say("ok")
            }
        }

        location /dapi/ {

            #access_by_lua_file /etc/nginx/lua/capture.lua;

            access_by_lua_file /etc/nginx/lua/capture_request.lua;

            body_filter_by_lua_file /etc/nginx/lua/capture_response.lua;

            log_by_lua_file /etc/nginx/lua/send_log.lua;

            proxy_set_header Host dapi.xxx.com;

            proxy_ssl_server_name on;
            proxy_ssl_name dapi.xxx.com;

            proxy_pass https://dapi/;
        }

        location /dfr/ {

            #access_by_lua_file /etc/nginx/lua/capture.lua;
            
            access_by_lua_file /etc/nginx/lua/capture_request.lua;

            body_filter_by_lua_file /etc/nginx/lua/capture_response.lua;

            log_by_lua_file /etc/nginx/lua/send_log.lua;

            proxy_set_header Host dfr.xxx.com;

            proxy_ssl_server_name on;
            proxy_ssl_name dapi.xxx.com;

            proxy_pass https://dfr/;
        }
    }
}
